---
title: "Anime Recommendation"
author: "Christina H Thai"
date: "3/31/2020"
output: html_document
---


```{r}
library(sqldf)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(plotly)
```


```{r}
anime = read.csv("anime.csv")
rating = read.csv("rating.csv")
```


This document seeks to utilize the library *sqldf* to determine the answer to the following questions: <br>

1. Is there a correlation between fan base size and number of episodes?

2. For active members, which genres are most popular (is there a stronger fan base for specific genres)?


#Data Cleaning
```{r}
str(anime)
str(rating)
```


```{r}
#Which columns to  change to character vec
anime = anime %>% mutate(genre = as.character(genre),
                         episodes = as.integer(episodes))


```

```{r}
str(anime)

```



```{r}

#Expand the dataframe into genres 
anime %>% filter(!is.na(rating)) %>% 
  mutate(genre = map(genre, ~ strsplit(.x, ", ") %>% unlist())) %>% 
  unnest(genre) ->
  shows_by_genre
```

```{r}
g = ggplot(data = shows_by_genre , 
       mapping = aes(x = rating, fill = genre)) +geom_density(aes(fill = genre), alpha = 0.4)
ggplotly(g)
```



```{r}
shows_by_genre %>% group_by(genre) %>% 
  select(name, genre, rating)  %>% 
  summarize(mean_by_genre = mean(rating, na.rm = TRUE), 
            min_rating = min(rating, na.rm = TRUE),
            max_rating = max(rating, na.rm = TRUE))
```
